source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /blog/:year/:month/:day/:title.html
auto: true
pygments: true
safe: false
blogname: "Madhur@Web:~# :(){ :|: & };:"
blogurl: http://madhur.co.in
feedname: http://feeds.feedburner.com/madhur
github_user: madhur

projects:
  
  tagger: &tagger
    title:     Tagger
    icon:      Tagger.png
    version:   1.5.1
    languages: [Objective C, C++, Ruby]
    changelog: true
    apidocs:   false
    download:  https://github.com/downloads/Bilalh/Tagger/Tagger_1.5.1.zip
    support:   https://github.com/Bilalh/tagger/issues
    iusethis:  mediatagger
    # alternativeto: media-tagger
    macupdate: 41285
    gallery:   
      - title: Multiple File Editing
        image: s001.png 
        description: >
           Multiple files can be edited at once.

      - title: Album art
        image: s002.png 
        description: >
           Tagger supports editings album art, album art can extracted by dragging the image to a directory.

      - title: Quicklook
        image: s003.png 
        description: >
           Tagger supports Quicklook to play the audio files.

      - title: Finder Labels
        image: s004.png 
        description: >
           Tagger supports editing Finder labels.

      - title: File Renaming
        image: s005.png 
        description: >
           Tagger supports batch file renaming using the field of the audio files.

      - title: Auto Tagging - Search
        image: s006.png 
        description: >
           Tagger supports searching in multiple languages, clicking on a row open the web page of album.

      - title: Auto Tagging - Results
        image: s007.png 
        description: >
          The field to be tagged can be changed. 

      - title: Auto Tagging - languages 
        image: s008.png 
        description: >
          The language can also be specifed when auto tagging,

      - title: Preferences 
        image: s009.png 
        description: >
           The columns in the table can be chosen. The starting folder can also be specifed.
    

    features:
        - title: Aqua User Interface
          icon:  gui.png
          description: >
            Intuitive user interface based on technology that features everything you would expect from a good  Mac application, including time savers like drag and drop, Quick Look, and more.  

        - title: Batch Operations
          #icon : gui.png
          description: >
            Multiple file tag editing is easy since Tagger supports applying changes to a selection of files.

        - title: Auto Tagging
          #icon : gui.png
          description: >
            Tagger can Search for the tags off the internet (using vgmdb). Tagger will retrieve matching result and allows you to browse the result and finally apply the tags to the selection.

        - title: Superior Tag Support
          #icon : gui.png
          description: Tagger supports nearly all of the tags of both MP3 and MP4

        - title: File Renaming
          #icon : gui.png
          description: >
            Tagger supports batch renaming of files from their tags, using any format you choose e.g. 01 - Title.

        - title: Table view 
          #icon : gui.png
          description: >
            Tagger has a sortable table view (which supports all the tag fields) for easy editing.

        - title: Convenient Folder Operations  
          #icon : gui.png
          description: >
            Tagger allows you set a default folder, allows draging audio files and folders to the dock icon or table view to go directly to the file and more.   

        - title: Finder Labels
          #icon : gui.png
          description: >
            Finder labels are supported for easy organisation. They can be assigned with a Finder like right click menu. 

        - title: Tag Manipulation
          #icon : gui.png
          description: >
            Tagger supports changing the capitalization (Uppercase, lowercase, and Title Case) for readability. It also supports renumbering of files and triming whitespace.

        - title: Artwork
          #icon : gui.png
          description: >
            Tagger supports embeding artwork in audio files. The image can also be dragged to a folder e.g. the desktop using a customised format.
    

    name:        tagger
    oneline:     >
      An tag editor for audio files, that support auto tagging.
    description: >
      Tagger is an application that auto tags audio files. It also supports batch tag editing. 


  mplayer-last.fm-scrobbler: &mplayer-lastfm
    title:     MPlayer last.fm scrobbler
    languages: [Shell, C++]
    description: >
      A command line application that plays audio files with MPlayer and scrobbles them to last.fm. Supports mp3, mp4, flac and ogg.
  
  media: &media
    title:       Media
    languages:   [C, SQL, Man Pages]
    description: >
      A efficient program that keeps track of tv episodes, also has a nice interface to mplayer, has lots of options see man pages for details.
  
  Audio-Sync: &Audio-Sync
    title:       Audio Sync
    languages:   [Ruby, Objective C]
    description: >
     Syncs the specified playlist in iTunes to the specified location, only copying the songs that have changed.ddddddddddddddddddddddddddddddddd
  
  Shell-Tunes: &Shell-Tunes
    title:       Shell Tunes
    languages:   [Shell, Applescript]
    description: >
      Control itunes from the command line, over 40 commands inculding play/pause, mute/unmute, playlist and play random album. Also inculdes also scripts for getting data from itunes.


  MPlayer-OSX-Extended: &MPlayer-OSX-Extended
    title:       MPlayer OSX Extended
    icon:        MPlayer-OSX-Extended.png
    languages:   [Objective C, Icons]
    download:    https://github.com/downloads/Bilalh/MPlayer-OSX-Extended/MPlayer%20OSX%20Extended.zip
    readme_name: Main
    changelog:   true
    apidocs:     true
    changelog_location: https://raw.github.com/Bilalh/MPlayer-OSX-Extended/readme/CHANGELOG.md
    changelog_heading_hash: true
    apidocs_name: Help
    name:         mplayer-osx-extended
    oneline:      >
      Video player leveraging the power of the MPlayer with extra features.
    description:  >
      MPlayer OSX Extended is a video player leveraging the power of the MPlayer and FFmpeg. I have contributed icons and some features to the project and upto data binaries.
  

  BHDraggableImageView: &BHDraggableImageView
    title:       BHDraggableImageView
    languages:   [Objective C]
    description: >
      NSImageView where the image can be dragged to any other image source and also as a file. Supports Garbage Collection
  

  autoDoc: &autoDoc
    title:       AutoDoc
    languages:   [Ruby]
    description: >
      Creates Doxygen comments for methods/functions in C and Objective C
  
  Web-Utilities: &Web-Utilities
    title:       Web Utilities
    languages:   [Ruby]
    description: >
      Scripts for transforming html, including removing elements by CSS/XPath and transforming Metawiki webpages to epub friendly html with chapters for all the headings.
  
  
  Bash-Scripts: &Bash-Scripts
    title:       Shell Utilities
    languages:   [Shell]
    description: >
      A collection of scripts and alias for use at command line. Includes a function to extract any kind archive (save you from remembering all the tar flags) and finding your ip. Also includes scripts for for the bit rate and other information from audio files.
  
  MKV-Utilities: &MKV-Utilities
    title:       MKV Utlities
    languages:   [Shell]
    description: >
      Scripts to easily join, split and extracts mkv files. Also has scripts to do lossless convertion of mkv to mp4 (with subtitles) and mp4 to mkv. The scripts can also extract all fonts and subtitles from a set of mkvs. Also contains a Java app for creating mkv chapters.
  
  
  Finder-Utilities: &Finder-Utilities
    title:       Finder Utilities
    languages:   [Applescript, Shell, Ruby]
    description: >
      Set of scripts for controlling Finder, includes get the path of the selected Finder item, setting labels, timestamps files a script for mac that goes to the location of the frontmost Finder window in the Terminal.dddddddddddddddddddddd dfdsfsdfsdfsdfsdf
  
  # 
  # Applescript Utilities:
  #   title:       Applescript Utilities
  #   languages:   Applescript
  #   description: >
  #     A collection of use applscripts that inculding file labeling, 'fn lock', timestamping files and controlling mplayer.
  
  
  Scripts: &Scripts
    title:       Utilities
    languages:   [Shell, Ruby, Applescript, Python, Other]
    description: >
      Scripts that don’t fit any of the other collections, includes scripts for re-encoding movies file for phones, doing a diff on LaTeX and removing duplicates lines from a files.
  
  
  bashmarks: &bashmarks
    title:       Bashmarks
    languages:   [Shell]
    name:   bashmarks
    oneline: >
      Directory bookmarks for the terminal with adddition features.
    description: >
      Fork of bashmarks (a script that allows you to save and jump to commonly used directories. with supports for tab completion.) that supports open the bookmark in Finder and perform and command after using a bookmark e.g. `g bookmarkname ls` changes the directory to the bookmark then preforms ls.
  


featured_project: 
  -  
    *tagger
  -
      *bashmarks
  -
    *MPlayer-OSX-Extended