source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /blog/:year/:month/:day/:title.html
highlighter: pygments
safe: false
blogname: "Madhur's Blog"
blogurl: http://madhur.co.in
feedname: http://feeds.feedburner.com/madhur
github_user: madhur
mode: prod
generate_projects: false
excerpt_separator: ""
exclude: [projects1]
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "lax_spacing"]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      location: New Delhi, India
      time: 9:00 PM
      layout: blog-post

gems:
  - jekyll-sitemap