source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /blog/:year/:month/:day/:title.html
pygments: true
safe: false
blogname: "Madhur's Blog"
blogurl: http://madhur.co.in
feedname: http://feeds.feedburner.com/madhur
github_user: madhur

