source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /blog/:year/:month/:day/:title.html
highlighter: pygments
safe: false
blogname: "Madhur's Blog"
blogurl: http://madhur.co.in
feedname: http://feeds.feedburner.com/madhur
github_user: madhur
mode: dev
exclude: [projects]
excerpt_separator: ""

markdown: kramdown

